# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
    ]
